/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_16bit_12 (
    input [15:0] a,
    input [15:0] b,
    input [0:0] alufn,
    output reg [15:0] s,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  wire [16-1:0] M_adder1_s;
  reg [16-1:0] M_adder1_a;
  reg [16-1:0] M_adder1_b;
  reg [1-1:0] M_adder1_alufn;
  adder_16bit_1_24 adder1 (
    .a(M_adder1_a),
    .b(M_adder1_b),
    .alufn(M_adder1_alufn),
    .s(M_adder1_s)
  );
  
  wire [1-1:0] M_adder2_z;
  wire [1-1:0] M_adder2_v;
  wire [1-1:0] M_adder2_n;
  reg [1-1:0] M_adder2_a;
  reg [1-1:0] M_adder2_b;
  reg [1-1:0] M_adder2_alufn;
  reg [16-1:0] M_adder2_s;
  adder_16bit_2_25 adder2 (
    .a(M_adder2_a),
    .b(M_adder2_b),
    .alufn(M_adder2_alufn),
    .s(M_adder2_s),
    .z(M_adder2_z),
    .v(M_adder2_v),
    .n(M_adder2_n)
  );
  
  always @* begin
    M_adder1_a[0+15-:16] = a[0+15-:16];
    M_adder1_b[0+15-:16] = b[0+15-:16];
    M_adder1_alufn[0+0-:1] = alufn[0+0-:1];
    M_adder2_a = a[15+0-:1];
    M_adder2_b = b[15+0-:1];
    M_adder2_alufn[0+0-:1] = alufn[0+0-:1];
    M_adder2_s[0+15-:16] = M_adder1_s[0+15-:16];
    s[0+15-:16] = M_adder1_s[0+15-:16];
    z = M_adder2_z;
    v = M_adder2_v;
    n = M_adder2_n;
  end
endmodule
