/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module random_problem_9 (
    input clk,
    input rst,
    input next,
    input [31:0] seed,
    output reg [15:0] num
  );
  
  
  
  wire [32-1:0] M_rng_num;
  reg [1-1:0] M_rng_clk;
  reg [1-1:0] M_rng_rst;
  reg [1-1:0] M_rng_next;
  reg [32-1:0] M_rng_seed;
  pn_gen_38 rng (
    .clk(M_rng_clk),
    .rst(M_rng_rst),
    .next(M_rng_next),
    .seed(M_rng_seed),
    .num(M_rng_num)
  );
  
  always @* begin
    M_rng_clk = clk;
    M_rng_rst = rst;
    M_rng_seed = seed;
    M_rng_next = next;
    if (M_rng_num > 7'h63) begin
      num = M_rng_num[0+5-:6];
    end else begin
      num = M_rng_num[0+6-:7];
    end
  end
endmodule
