/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module dual_seven_seg_3 (
    input [15:0] char,
    output reg [6:0] segs1,
    output reg [6:0] segs2
  );
  
  
  
  always @* begin
    
    case (char)
      1'h0: begin
        segs1 = 7'h3f;
        segs2 = 7'h3f;
      end
      1'h1: begin
        segs1 = 7'h06;
        segs2 = 7'h3f;
      end
      2'h2: begin
        segs1 = 7'h5b;
        segs2 = 7'h3f;
      end
      2'h3: begin
        segs1 = 7'h4f;
        segs2 = 7'h3f;
      end
      3'h4: begin
        segs1 = 7'h66;
        segs2 = 7'h3f;
      end
      3'h5: begin
        segs1 = 7'h6d;
        segs2 = 7'h3f;
      end
      3'h6: begin
        segs1 = 7'h7d;
        segs2 = 7'h3f;
      end
      3'h7: begin
        segs1 = 7'h07;
        segs2 = 7'h3f;
      end
      4'h8: begin
        segs1 = 7'h7f;
        segs2 = 7'h3f;
      end
      4'h9: begin
        segs1 = 7'h67;
        segs2 = 7'h3f;
      end
      4'ha: begin
        segs1 = 7'h3f;
        segs2 = 7'h06;
      end
      4'hb: begin
        segs1 = 7'h06;
        segs2 = 7'h06;
      end
      4'hc: begin
        segs1 = 7'h5b;
        segs2 = 7'h06;
      end
      4'hd: begin
        segs1 = 7'h4f;
        segs2 = 7'h06;
      end
      4'he: begin
        segs1 = 7'h66;
        segs2 = 7'h06;
      end
      4'hf: begin
        segs1 = 7'h6d;
        segs2 = 7'h06;
      end
      5'h10: begin
        segs1 = 7'h7d;
        segs2 = 7'h06;
      end
      5'h11: begin
        segs1 = 7'h07;
        segs2 = 7'h06;
      end
      5'h12: begin
        segs1 = 7'h7f;
        segs2 = 7'h06;
      end
      5'h13: begin
        segs1 = 7'h67;
        segs2 = 7'h06;
      end
      5'h14: begin
        segs1 = 7'h3f;
        segs2 = 7'h5b;
      end
      5'h15: begin
        segs1 = 7'h06;
        segs2 = 7'h5b;
      end
      5'h16: begin
        segs1 = 7'h5b;
        segs2 = 7'h5b;
      end
      5'h17: begin
        segs1 = 7'h4f;
        segs2 = 7'h5b;
      end
      5'h18: begin
        segs1 = 7'h66;
        segs2 = 7'h5b;
      end
      5'h19: begin
        segs1 = 7'h6d;
        segs2 = 7'h5b;
      end
      5'h1a: begin
        segs1 = 7'h7d;
        segs2 = 7'h5b;
      end
      5'h1b: begin
        segs1 = 7'h07;
        segs2 = 7'h5b;
      end
      5'h1c: begin
        segs1 = 7'h7f;
        segs2 = 7'h5b;
      end
      5'h1d: begin
        segs1 = 7'h67;
        segs2 = 7'h5b;
      end
      5'h1e: begin
        segs1 = 7'h3f;
        segs2 = 7'h4f;
      end
      5'h1f: begin
        segs1 = 7'h06;
        segs2 = 7'h4f;
      end
      6'h20: begin
        segs1 = 7'h5b;
        segs2 = 7'h4f;
      end
      6'h21: begin
        segs1 = 7'h4f;
        segs2 = 7'h4f;
      end
      6'h22: begin
        segs1 = 7'h66;
        segs2 = 7'h4f;
      end
      6'h23: begin
        segs1 = 7'h6d;
        segs2 = 7'h4f;
      end
      6'h24: begin
        segs1 = 7'h7d;
        segs2 = 7'h4f;
      end
      6'h25: begin
        segs1 = 7'h07;
        segs2 = 7'h4f;
      end
      6'h26: begin
        segs1 = 7'h7f;
        segs2 = 7'h4f;
      end
      6'h27: begin
        segs1 = 7'h67;
        segs2 = 7'h4f;
      end
      6'h28: begin
        segs1 = 7'h3f;
        segs2 = 7'h66;
      end
      6'h29: begin
        segs1 = 7'h06;
        segs2 = 7'h66;
      end
      6'h2a: begin
        segs1 = 7'h5b;
        segs2 = 7'h66;
      end
      6'h2b: begin
        segs1 = 7'h4f;
        segs2 = 7'h66;
      end
      6'h2c: begin
        segs1 = 7'h66;
        segs2 = 7'h66;
      end
      6'h2d: begin
        segs1 = 7'h6d;
        segs2 = 7'h66;
      end
      6'h2e: begin
        segs1 = 7'h7d;
        segs2 = 7'h66;
      end
      6'h2f: begin
        segs1 = 7'h07;
        segs2 = 7'h66;
      end
      6'h30: begin
        segs1 = 7'h7f;
        segs2 = 7'h66;
      end
      6'h31: begin
        segs1 = 7'h67;
        segs2 = 7'h66;
      end
      6'h32: begin
        segs1 = 7'h3f;
        segs2 = 7'h6d;
      end
      6'h33: begin
        segs1 = 7'h06;
        segs2 = 7'h6d;
      end
      6'h34: begin
        segs1 = 7'h5b;
        segs2 = 7'h6d;
      end
      6'h35: begin
        segs1 = 7'h4f;
        segs2 = 7'h6d;
      end
      6'h36: begin
        segs1 = 7'h66;
        segs2 = 7'h6d;
      end
      6'h37: begin
        segs1 = 7'h6d;
        segs2 = 7'h6d;
      end
      6'h38: begin
        segs1 = 7'h7d;
        segs2 = 7'h6d;
      end
      6'h39: begin
        segs1 = 7'h07;
        segs2 = 7'h6d;
      end
      6'h3a: begin
        segs1 = 7'h7f;
        segs2 = 7'h6d;
      end
      6'h3b: begin
        segs1 = 7'h67;
        segs2 = 7'h6d;
      end
      6'h3c: begin
        segs1 = 7'h3f;
        segs2 = 7'h7d;
      end
      6'h3d: begin
        segs1 = 7'h06;
        segs2 = 7'h7d;
      end
      6'h3e: begin
        segs1 = 7'h5b;
        segs2 = 7'h7d;
      end
      6'h3f: begin
        segs1 = 7'h4f;
        segs2 = 7'h7d;
      end
      7'h40: begin
        segs1 = 7'h66;
        segs2 = 7'h7d;
      end
      7'h41: begin
        segs1 = 7'h6d;
        segs2 = 7'h7d;
      end
      7'h42: begin
        segs1 = 7'h7d;
        segs2 = 7'h7d;
      end
      7'h43: begin
        segs1 = 7'h07;
        segs2 = 7'h7d;
      end
      7'h44: begin
        segs1 = 7'h7f;
        segs2 = 7'h7d;
      end
      7'h45: begin
        segs1 = 7'h67;
        segs2 = 7'h7d;
      end
      7'h46: begin
        segs1 = 7'h3f;
        segs2 = 7'h07;
      end
      7'h47: begin
        segs1 = 7'h06;
        segs2 = 7'h07;
      end
      7'h48: begin
        segs1 = 7'h5b;
        segs2 = 7'h07;
      end
      7'h49: begin
        segs1 = 7'h4f;
        segs2 = 7'h07;
      end
      7'h4a: begin
        segs1 = 7'h66;
        segs2 = 7'h07;
      end
      7'h4b: begin
        segs1 = 7'h6d;
        segs2 = 7'h07;
      end
      7'h4c: begin
        segs1 = 7'h7d;
        segs2 = 7'h07;
      end
      7'h4d: begin
        segs1 = 7'h07;
        segs2 = 7'h07;
      end
      7'h4e: begin
        segs1 = 7'h7f;
        segs2 = 7'h07;
      end
      7'h4f: begin
        segs1 = 7'h67;
        segs2 = 7'h07;
      end
      7'h50: begin
        segs1 = 7'h3f;
        segs2 = 7'h7f;
      end
      7'h51: begin
        segs1 = 7'h06;
        segs2 = 7'h7f;
      end
      7'h52: begin
        segs1 = 7'h5b;
        segs2 = 7'h7f;
      end
      7'h53: begin
        segs1 = 7'h4f;
        segs2 = 7'h7f;
      end
      7'h54: begin
        segs1 = 7'h66;
        segs2 = 7'h7f;
      end
      7'h55: begin
        segs1 = 7'h6d;
        segs2 = 7'h7f;
      end
      7'h56: begin
        segs1 = 7'h7d;
        segs2 = 7'h7f;
      end
      7'h57: begin
        segs1 = 7'h07;
        segs2 = 7'h7f;
      end
      7'h58: begin
        segs1 = 7'h7f;
        segs2 = 7'h7f;
      end
      7'h59: begin
        segs1 = 7'h67;
        segs2 = 7'h7f;
      end
      7'h5a: begin
        segs1 = 7'h3f;
        segs2 = 7'h67;
      end
      7'h5b: begin
        segs1 = 7'h06;
        segs2 = 7'h67;
      end
      7'h5c: begin
        segs1 = 7'h5b;
        segs2 = 7'h67;
      end
      7'h5d: begin
        segs1 = 7'h4f;
        segs2 = 7'h67;
      end
      7'h5e: begin
        segs1 = 7'h66;
        segs2 = 7'h67;
      end
      7'h5f: begin
        segs1 = 7'h6d;
        segs2 = 7'h67;
      end
      7'h60: begin
        segs1 = 7'h7d;
        segs2 = 7'h67;
      end
      7'h61: begin
        segs1 = 7'h07;
        segs2 = 7'h67;
      end
      7'h62: begin
        segs1 = 7'h7f;
        segs2 = 7'h67;
      end
      7'h63: begin
        segs1 = 7'h67;
        segs2 = 7'h67;
      end
      default: begin
        segs1 = 7'h40;
        segs2 = 7'h40;
      end
    endcase
  end
endmodule
